### ISSUE TITLE
Visual Styling

### ISSUE THREAD

**Issue by alexpaxton** [Sciator/giraffe-components-concepts#1]
![Screen Shot 2020-11-12 at 4 12 13 PM](https://user-images.githubusercontent.com/2433762/99011843-da253a80-2501-11eb-9ff3-f097f3eb0abf.png)

- Main label text size & color are optionally configurable
  - Defaults to `13px` and `InfluxColors.Ghost`
- Label text size & color are optionally configurable
  - Defaults to `11px` and `InfluxColors.Forge`
- Axes text size & color are optionally configurable
  - Defaults to `11px` and `InfluxColors.Forge`
- Empty bar color is `InfluxColors.Kevlar`
- Rounded outer bar corners
  - Used a `clipPath` element (see below)

Clip path is an easy way to round only the outside corners regardless of how many segments there are in the gauge

```jsx
<>
  <defs>
    <clipPath id="rounded-bar">
      <rect rx={4} ry={4} y={gaugeBarY} width={barWidth} height={gaugeHeight} />
    </clipPath>
  </defs>
  <BarBackground  clip="rounded-bar" />
</>
```

Bar Background
```jsx
<rect clipPath={`url(#${clip})`} />
```

**Comment by Sciator** [comment]
All done! 🎉
